import { MARKETING_PERMISSIONS as P } from "./marketingPermissions";

export const MARKETING_ADMIN_ROLES = {
  MARKETING_REVIEWER: {
    name: "Marketing Reviewer",
    permissions: [P.VIEW, P.CAMPAIGN_VIEW, P.CAMPAIGN_APPROVE, P.CAMPAIGN_REJECT, P.AD_VIEW, P.AD_APPROVE, P.AD_REJECT, P.AUDIT_VIEW],
  },
  MARKETING_MANAGER: {
    name: "Marketing Manager",
    permissions: [P.VIEW, P.CAMPAIGN_VIEW, P.CAMPAIGN_CREATE, P.CAMPAIGN_EDIT, P.CAMPAIGN_APPROVE, P.CAMPAIGN_PUBLISH, P.CAMPAIGN_REJECT, P.CAMPAIGN_PAUSE, P.CAMPAIGN_RESUME, P.CAMPAIGN_ARCHIVE, P.AD_VIEW, P.AD_CREATE, P.AD_EDIT, P.AD_APPROVE, P.AD_PUBLISH, P.AD_REJECT, P.AD_PAUSE, P.AD_RESUME, P.AD_ARCHIVE, P.ADVERTISER_VIEW, P.AUDIENCE_VIEW, P.PLACEMENT_VIEW, P.ANALYTICS_VIEW, P.BILLING_VIEW, P.AUDIT_VIEW],
  },
  MARKETING_ENFORCEMENT: {
    name: "Marketing Enforcement",
    permissions: [P.VIEW, P.CAMPAIGN_VIEW, P.CAMPAIGN_REJECT, P.CAMPAIGN_BLOCK, P.CAMPAIGN_UNBLOCK, P.AD_VIEW, P.AD_REJECT, P.AD_BLOCK, P.AD_UNBLOCK, P.AUDIT_VIEW],
  },
  MARKETING_SUPER_ADMIN: { name: "Marketing Super Admin", permissions: Object.values(P) },
} as const;
