/**
 * organization-badge.schema.ts
 * -----------------------------------------------------------------------------
 * Generic Fockis Organization Membership Badge.
 *
 * This is NOT church-specific.
 *
 * The same badge system can represent:
 *
 *   - Church members
 *   - School students
 *   - Employees
 *   - Nonprofit members
 *   - Team members
 *   - Club members
 *   - Community members
 *   - Organization volunteers
 *   - Organization administrators
 *   - Other organization identities
 *
 * ONE ACTIVE MEMBERSHIP = ONE BADGE
 *
 * The badge is linked permanently to:
 *
 *   organizationId
 *   membershipId
 *   userId
 *
 * Personal/private information is intentionally NOT stored in the QR value.
 * -----------------------------------------------------------------------------
 */

import {
  Prop,
  Schema,
  SchemaFactory,
} from '@nestjs/mongoose';

import {
  Document,
  Types,
} from 'mongoose';

export type OrganizationBadgeDocument =
  OrganizationBadge & Document;

@Schema({
  timestamps: true,
  collection: 'organization_badges',
})
export class OrganizationBadge {
  /* ==========================================================================
     ORGANIZATION
     ========================================================================== */

  @Prop({
    type: Types.ObjectId,
    ref: 'Organization',
    required: true,
    index: true,
  })
  organizationId!: Types.ObjectId;

  /* ==========================================================================
     MEMBERSHIP
     ========================================================================== */

  /**
   * The membership this badge represents.
   *
   * One membership can have only one badge.
   */
  @Prop({
    type: Types.ObjectId,
    ref: 'Membership',
    required: true,
    unique: true,
    index: true,
  })
  membershipId!: Types.ObjectId;

  /* ==========================================================================
     USER
     ========================================================================== */

  @Prop({
    type: Types.ObjectId,
    required: true,
    index: true,
  })
  userId!: Types.ObjectId;

  /* ==========================================================================
     MEMBER NUMBER
     ========================================================================== */

  /**
   * Human-readable organization member number.
   *
   * Example:
   *
   *   ORG-000001
   *
   * This is generated by Fockis.
   */
  @Prop({
    type: String,
    required: true,
    trim: true,
    index: true,
  })
  memberNumber!: string;

  /* ==========================================================================
     MEMBER INFORMATION
     ========================================================================== */

  @Prop({
    type: String,
    required: true,
    trim: true,
  })
  displayName!: string;

  @Prop({
    type: String,
    default: null,
  })
  avatarUrl?: string | null;

  /* ==========================================================================
     ORGANIZATION INFORMATION
     ========================================================================== */

  @Prop({
    type: String,
    required: true,
    trim: true,
  })
  organizationName!: string;

  @Prop({
    type: String,
    default: null,
  })
  organizationLogoUrl?: string | null;

  @Prop({
    type: String,
    default: null,
    trim: true,
  })
  organizationType?: string | null;

  /* ==========================================================================
     MEMBERSHIP INFORMATION
     ========================================================================== */

  @Prop({
    type: String,
    required: true,
    trim: true,
  })
  role!: string;

  @Prop({
    type: String,
    required: true,
    trim: true,
  })
  status!: string;

  @Prop({
    type: Date,
    default: null,
  })
  joinedAt?: Date | null;

  /* ==========================================================================
     DEPARTMENTS
     ========================================================================== */

  @Prop({
    type: [String],
    default: [],
  })
  departmentNames!: string[];

  /* ==========================================================================
     GROUPS
     ========================================================================== */

  @Prop({
    type: [String],
    default: [],
  })
  groupNames!: string[];

  /* ==========================================================================
     QR VERIFICATION
     ========================================================================== */

  /**
   * Stable non-sensitive QR value.
   *
   * Example:
   *
   *   fockis:organization-badge:<organizationId>:<membershipId>
   *
   * NEVER put:
   *
   *   - password
   *   - email
   *   - phone
   *   - address
   *   - date of birth
   *   - private notes
   *
   * inside this value.
   */
  @Prop({
    type: String,
    required: true,
    unique: true,
    index: true,
  })
  qrCodeValue!: string;

  /* ==========================================================================
     BADGE STATE
     ========================================================================== */

  @Prop({
    type: Boolean,
    default: true,
    index: true,
  })
  active!: boolean;

  /* ==========================================================================
     ISSUANCE
     ========================================================================== */

  @Prop({
    type: Date,
    default: Date.now,
  })
  issuedAt!: Date;

  /* ==========================================================================
     TIMESTAMPS
     ========================================================================== */

  createdAt?: Date;

  updatedAt?: Date;
}

/* ============================================================================
   SCHEMA
============================================================================ */

export const OrganizationBadgeSchema =
  SchemaFactory.createForClass(
    OrganizationBadge,
  );

/* ============================================================================
   INDEXES
============================================================================ */

/**
 * Organization + membership lookup.
 */
OrganizationBadgeSchema.index({
  organizationId: 1,
  membershipId: 1,
});

/**
 * Organization + user lookup.
 */
OrganizationBadgeSchema.index({
  organizationId: 1,
  userId: 1,
});

/**
 * Organization + active badges.
 */
OrganizationBadgeSchema.index({
  organizationId: 1,
  active: 1,
});