export enum CampaignStatus { DRAFT='DRAFT', SCHEDULED='SCHEDULED', SENDING='SENDING', SENT='SENT', PAUSED='PAUSED', CANCELLED='CANCELLED' }
export enum CampaignType { EMAIL='EMAIL', SMS='SMS', SOCIAL='SOCIAL' }
export enum ContactStatus { SUBSCRIBED='SUBSCRIBED', UNSUBSCRIBED='UNSUBSCRIBED', CLEANED='CLEANED', PENDING='PENDING' }
export enum AutomationStatus { DRAFT='DRAFT', ACTIVE='ACTIVE', PAUSED='PAUSED' }
export enum JourneyStatus { DRAFT='DRAFT', ACTIVE='ACTIVE', PAUSED='PAUSED', ARCHIVED='ARCHIVED' }
export enum TransactionStatus { PENDING='PENDING', PAID='PAID', FAILED='FAILED', REFUNDED='REFUNDED' }
