import type {
  MusicGenre,
} from '../types/music.types';

import type {
  AccessOption,
  ContentTypeOption,
  CountryCurrency,
  FormState,
} from '../types/musicCreateRelease.types';

export const MAX_SERIES_EPISODES = 25;

export const COUNTRIES: CountryCurrency[] = [
  {
    code: 'US',
    name: 'United States',
    flag: '🇺🇸',
    currency: 'USD',
    currencyName: 'US Dollar',
    symbol: '$',
    locale: 'en-US',
    decimals: 2,
  },
  {
    code: 'HT',
    name: 'Haiti',
    flag: '🇭🇹',
    currency: 'HTG',
    currencyName: 'Haitian Gourde',
    symbol: 'G',
    locale: 'fr-HT',
    decimals: 2,
  },
  {
    code: 'CA',
    name: 'Canada',
    flag: '🇨🇦',
    currency: 'CAD',
    currencyName: 'Canadian Dollar',
    symbol: 'CA$',
    locale: 'en-CA',
    decimals: 2,
  },
  {
    code: 'DO',
    name: 'Dominican Republic',
    flag: '🇩🇴',
    currency: 'DOP',
    currencyName: 'Dominican Peso',
    symbol: 'RD$',
    locale: 'es-DO',
    decimals: 2,
  },
  {
    code: 'MX',
    name: 'Mexico',
    flag: '🇲🇽',
    currency: 'MXN',
    currencyName: 'Mexican Peso',
    symbol: 'MX$',
    locale: 'es-MX',
    decimals: 2,
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    flag: '🇬🇧',
    currency: 'GBP',
    currencyName: 'British Pound',
    symbol: '£',
    locale: 'en-GB',
    decimals: 2,
  },
  {
    code: 'FR',
    name: 'France',
    flag: '🇫🇷',
    currency: 'EUR',
    currencyName: 'Euro',
    symbol: '€',
    locale: 'fr-FR',
    decimals: 2,
  },
  {
    code: 'DE',
    name: 'Germany',
    flag: '🇩🇪',
    currency: 'EUR',
    currencyName: 'Euro',
    symbol: '€',
    locale: 'de-DE',
    decimals: 2,
  },
  {
    code: 'ES',
    name: 'Spain',
    flag: '🇪🇸',
    currency: 'EUR',
    currencyName: 'Euro',
    symbol: '€',
    locale: 'es-ES',
    decimals: 2,
  },
  {
    code: 'IT',
    name: 'Italy',
    flag: '🇮🇹',
    currency: 'EUR',
    currencyName: 'Euro',
    symbol: '€',
    locale: 'it-IT',
    decimals: 2,
  },
  {
    code: 'BR',
    name: 'Brazil',
    flag: '🇧🇷',
    currency: 'BRL',
    currencyName: 'Brazilian Real',
    symbol: 'R$',
    locale: 'pt-BR',
    decimals: 2,
  },
  {
    code: 'JM',
    name: 'Jamaica',
    flag: '🇯🇲',
    currency: 'JMD',
    currencyName: 'Jamaican Dollar',
    symbol: 'J$',
    locale: 'en-JM',
    decimals: 2,
  },
  {
    code: 'TT',
    name: 'Trinidad & Tobago',
    flag: '🇹🇹',
    currency: 'TTD',
    currencyName: 'Trinidad and Tobago Dollar',
    symbol: 'TT$',
    locale: 'en-TT',
    decimals: 2,
  },
  {
    code: 'NG',
    name: 'Nigeria',
    flag: '🇳🇬',
    currency: 'NGN',
    currencyName: 'Nigerian Naira',
    symbol: '₦',
    locale: 'en-NG',
    decimals: 2,
  },
  {
    code: 'GH',
    name: 'Ghana',
    flag: '🇬🇭',
    currency: 'GHS',
    currencyName: 'Ghanaian Cedi',
    symbol: 'GH₵',
    locale: 'en-GH',
    decimals: 2,
  },
  {
    code: 'KE',
    name: 'Kenya',
    flag: '🇰🇪',
    currency: 'KES',
    currencyName: 'Kenyan Shilling',
    symbol: 'KSh',
    locale: 'en-KE',
    decimals: 2,
  },
  {
    code: 'ZA',
    name: 'South Africa',
    flag: '🇿🇦',
    currency: 'ZAR',
    currencyName: 'South African Rand',
    symbol: 'R',
    locale: 'en-ZA',
    decimals: 2,
  },
  {
    code: 'IN',
    name: 'India',
    flag: '🇮🇳',
    currency: 'INR',
    currencyName: 'Indian Rupee',
    symbol: '₹',
    locale: 'en-IN',
    decimals: 2,
  },
  {
    code: 'AU',
    name: 'Australia',
    flag: '🇦🇺',
    currency: 'AUD',
    currencyName: 'Australian Dollar',
    symbol: 'A$',
    locale: 'en-AU',
    decimals: 2,
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    flag: '🇳🇿',
    currency: 'NZD',
    currencyName: 'New Zealand Dollar',
    symbol: 'NZ$',
    locale: 'en-NZ',
    decimals: 2,
  },
  {
    code: 'JP',
    name: 'Japan',
    flag: '🇯🇵',
    currency: 'JPY',
    currencyName: 'Japanese Yen',
    symbol: '¥',
    locale: 'ja-JP',
    decimals: 0,
  },
];

export const INITIAL_FORM: FormState = {
  contentType: 'single',
  mediaKind: 'audio',

  title: '',
  description: '',
  genre: '',
  tags: '',

  mediaUrl: '',
  coverImageUrl: '',

  accessType: 'free',

  price: '0',
  previewDurationSeconds: '30',

  releaseDate: '',

  isFeatured: false,
  isExclusive: false,

  countryCode: 'US',
};

export const CONTENT_TYPES: ContentTypeOption[] = [
  {
    value: 'single',
    label: 'Single',
    description: 'Release one song as a standalone release.',
    mediaKind: 'audio',
    icon: '🎵',
    category: 'music',
  },
  {
    value: 'song',
    label: 'Song',
    description: 'Publish an individual track.',
    mediaKind: 'audio',
    icon: '🎧',
    category: 'music',
  },
  {
    value: 'album',
    label: 'Album',
    description: 'Create a complete album release.',
    mediaKind: 'audio',
    icon: '💿',
    category: 'music',
  },
  {
    value: 'ep',
    label: 'EP',
    description: 'Publish a short collection of tracks.',
    mediaKind: 'audio',
    icon: '📀',
    category: 'music',
  },
  {
    value: 'beat',
    label: 'Beat',
    description: 'Sell or distribute an instrumental beat.',
    mediaKind: 'audio',
    icon: '🥁',
    category: 'music',
  },
  {
    value: 'instrumental',
    label: 'Instrumental',
    description: 'Publish an instrumental recording.',
    mediaKind: 'audio',
    icon: '🎹',
    category: 'music',
  },

  {
    value: 'music_video',
    label: 'Music Video',
    description: 'Publish a professional music video.',
    mediaKind: 'video',
    icon: '🎬',
    category: 'video',
  },
  {
    value: 'live_performance',
    label: 'Live Performance',
    description: 'Share a concert, stage performance or live session.',
    mediaKind: 'video',
    icon: '🎤',
    category: 'video',
  },
  {
    value: 'interview',
    label: 'Interview',
    description: 'Publish an artist, creator or industry interview.',
    mediaKind: 'video',
    icon: '🎙️',
    category: 'video',
  },
  {
    value: 'behind_the_scenes',
    label: 'Behind the Scenes',
    description: 'Share exclusive production and creator footage.',
    mediaKind: 'video',
    icon: '🎥',
    category: 'video',
  },
  {
    value: 'tutorial',
    label: 'Tutorial',
    description: 'Teach your audience something useful.',
    mediaKind: 'video',
    icon: '📚',
    category: 'video',
  },
  {
    value: 'exclusive_video',
    label: 'Exclusive Video',
    description: 'Publish premium or members-only video content.',
    mediaKind: 'video',
    icon: '⭐',
    category: 'video',
  },

  {
    value: 'movie',
    label: 'Movie',
    description: 'Publish a movie, short film or independent film.',
    mediaKind: 'video',
    icon: '🎞️',
    category: 'creator',
  },
  {
    value: 'fashion',
    label: 'Fashion',
    description: 'Publish fashion shows, looks or collections.',
    mediaKind: 'video',
    icon: '👗',
    category: 'creator',
  },
  {
    value: 'event',
    label: 'Event',
    description: 'Promote or publish an event or special occasion.',
    mediaKind: 'video',
    icon: '🎟️',
    category: 'creator',
  },
  {
    value: 'announcement',
    label: 'Announcement',
    description: 'Share important news or updates.',
    mediaKind: 'video',
    icon: '📢',
    category: 'creator',
  },
  {
    value: 'creator_update',
    label: 'Creator Update',
    description: 'Share a personal creator update.',
    mediaKind: 'video',
    icon: '✨',
    category: 'creator',
  },
];

export const ACCESS_OPTIONS: AccessOption[] = [
  {
    value: 'free',
    label: 'Free',
    description: 'Everyone can access the full content.',
  },
  {
    value: 'preview_paid',
    label: 'Preview + Paid',
    description: 'Give viewers a preview and charge for full access.',
  },
  {
    value: 'paid',
    label: 'Paid',
    description: 'Full access requires payment.',
  },
  {
    value: 'premium',
    label: 'Premium',
    description: 'Available to eligible premium members.',
  },
  {
    value: 'exclusive',
    label: 'Exclusive',
    description: 'Exclusive access for your selected audience.',
  },
];

export const GENRES: Array<{
  value: MusicGenre;
  label: string;
}> = [
  {
    value: 'hip_hop',
    label: 'Hip Hop',
  },
  {
    value: 'rnb',
    label: 'R&B',
  },
  {
    value: 'afrobeats',
    label: 'Afrobeats',
  },
  {
    value: 'amapiano',
    label: 'Amapiano',
  },
  {
    value: 'pop',
    label: 'Pop',
  },
  {
    value: 'rock',
    label: 'Rock',
  },
  {
    value: 'electronic',
    label: 'Electronic',
  },
  {
    value: 'gospel',
    label: 'Gospel',
  },
  {
    value: 'jazz',
    label: 'Jazz',
  },
  {
    value: 'latin',
    label: 'Latin',
  },
  {
    value: 'other',
    label: 'Other',
  },
];