import { MARKETING_PERMISSIONS } from "./marketingPermissions";

export const MARKETING_ADMIN_ROLES = {
  MARKETING_REVIEWER: {
    name: "Marketing Reviewer",
    permissions: [
      MARKETING_PERMISSIONS.VIEW,

      MARKETING_PERMISSIONS.CAMPAIGN_VIEW,
      MARKETING_PERMISSIONS.CAMPAIGN_APPROVE,
      MARKETING_PERMISSIONS.CAMPAIGN_REJECT,

      MARKETING_PERMISSIONS.AD_VIEW,
      MARKETING_PERMISSIONS.AD_APPROVE,
      MARKETING_PERMISSIONS.AD_REJECT,

      MARKETING_PERMISSIONS.AUDIT_VIEW,
    ],
  },

  MARKETING_MANAGER: {
    name: "Marketing Manager",
    permissions: [
      MARKETING_PERMISSIONS.VIEW,

      MARKETING_PERMISSIONS.CAMPAIGN_VIEW,
      MARKETING_PERMISSIONS.CAMPAIGN_CREATE,
      MARKETING_PERMISSIONS.CAMPAIGN_EDIT,
      MARKETING_PERMISSIONS.CAMPAIGN_APPROVE,
      MARKETING_PERMISSIONS.CAMPAIGN_PUBLISH,
      MARKETING_PERMISSIONS.CAMPAIGN_REJECT,
      MARKETING_PERMISSIONS.CAMPAIGN_PAUSE,
      MARKETING_PERMISSIONS.CAMPAIGN_RESUME,
      MARKETING_PERMISSIONS.CAMPAIGN_ARCHIVE,

      MARKETING_PERMISSIONS.AD_VIEW,
      MARKETING_PERMISSIONS.AD_CREATE,
      MARKETING_PERMISSIONS.AD_EDIT,
      MARKETING_PERMISSIONS.AD_APPROVE,
      MARKETING_PERMISSIONS.AD_PUBLISH,
      MARKETING_PERMISSIONS.AD_REJECT,
      MARKETING_PERMISSIONS.AD_PAUSE,
      MARKETING_PERMISSIONS.AD_RESUME,
      MARKETING_PERMISSIONS.AD_ARCHIVE,

      MARKETING_PERMISSIONS.ADVERTISER_VIEW,
      MARKETING_PERMISSIONS.AUDIENCE_VIEW,
      MARKETING_PERMISSIONS.PLACEMENT_VIEW,

      MARKETING_PERMISSIONS.ANALYTICS_VIEW,
      MARKETING_PERMISSIONS.BILLING_VIEW,
      MARKETING_PERMISSIONS.AUDIT_VIEW,
    ],
  },

  MARKETING_ENFORCEMENT: {
    name: "Marketing Enforcement",
    permissions: [
      MARKETING_PERMISSIONS.VIEW,

      MARKETING_PERMISSIONS.CAMPAIGN_VIEW,
      MARKETING_PERMISSIONS.CAMPAIGN_REJECT,
      MARKETING_PERMISSIONS.CAMPAIGN_BLOCK,
      MARKETING_PERMISSIONS.CAMPAIGN_UNBLOCK,

      MARKETING_PERMISSIONS.AD_VIEW,
      MARKETING_PERMISSIONS.AD_REJECT,
      MARKETING_PERMISSIONS.AD_BLOCK,
      MARKETING_PERMISSIONS.AD_UNBLOCK,

      MARKETING_PERMISSIONS.AUDIT_VIEW,
    ],
  },

  MARKETING_SUPER_ADMIN: {
    name: "Marketing Super Admin",
    permissions: Object.values(
      MARKETING_PERMISSIONS,
    ),
  },
} as const;