/**
 * ============================================================================
 * FOCKIS MESSAGES - REAL SOCKET HOOK
 * ============================================================================
 *
 * Handles:
 *
 *   - real-time messages
 *   - delivered/read state
 *   - typing indicators
 *   - presence
 *   - incoming calls
 *   - accepted calls
 *   - rejected calls
 *   - ended calls
 *   - WebRTC signaling events
 *
 * IMPORTANT:
 *
 * The actual WebRTC peer connection is NOT created here.
 *
 * This hook only receives the signaling messages and keeps the global
 * application state synchronized.
 *
 * The WebRTC hook/component will subscribe directly to:
 *
 *   webrtc:offer
 *   webrtc:answer
 *   webrtc:ice-candidate
 *
 * through messageSocket.onRaw().
 * ============================================================================
 */

import { useEffect } from "react";

import { messageSocket } from "../services/messageSocket";

import { useMessagesStore } from "../store/messagesStore";

import { useConversationsStore } from "../store/conversationsStore";

import { useCallStore, type Call } from "../store/callStore";

/* ============================================================================
   HELPERS
============================================================================ */

/**
 * Backend calls now have a real `callId`.
 *
 * Keep support for `id` as a compatibility fallback, but do not generate
 * random IDs for real server calls anymore.
 *
 * A random ID would break WebRTC signaling because the server expects the
 * exact callId generated by the backend.
 */
function getCallId(payload: any): string {
  const callId =
    payload?.callId ??
    payload?.id ??
    "";

  return String(callId).trim();
}

/**
 * Normalize the backend call type.
 */
function getCallType(
  value: unknown,
): "voice" | "video" {
  return value === "voice"
    ? "voice"
    : "video";
}

/**
 * Build a Call object from the backend payload.
 */
function buildCall(
  payload: any,
  fallbackStatus:
    | "incoming"
    | "outgoing"
    | "connecting"
    | "active"
    | "ended"
    | "rejected",
): Call | null {
  const callId = getCallId(payload);

  if (!callId) {
    console.warn(
      "[FOCKIS CALL] Ignoring call event without callId",
      payload,
    );

    return null;
  }

  const callerId = String(
    payload?.callerId ?? "",
  ).trim();

  const receiverIdValue =
    payload?.receiverId;

  const receiverId =
    receiverIdValue !== undefined &&
    receiverIdValue !== null &&
    String(receiverIdValue).trim()
      ? String(receiverIdValue)
      : undefined;

  return {
    id: callId,

    callerId,

    receiverId,

    type: getCallType(
      payload?.type,
    ),

    createdAt:
      payload?.createdAt ??
      payload?.acceptedAt ??
      new Date().toISOString(),

    acceptedAt:
      payload?.acceptedAt
        ? String(payload.acceptedAt)
        : undefined,

    status: fallbackStatus,

    participantName:
      payload?.participantName
        ? String(payload.participantName)
        : undefined,

    participantAvatar:
      payload?.participantAvatar
        ? String(payload.participantAvatar)
        : undefined,
  };
}

/* ============================================================================
   HOOK
============================================================================ */

export function useMessageSocket(): void {
  const setTyping =
    useMessagesStore(
      (state) => state.setTyping,
    );

  const receiveMessage =
    useMessagesStore(
      (state) => state.receiveMessage,
    );

  const updatePresence =
    useConversationsStore(
      (state) => state.updatePresence,
    );

  useEffect(() => {
    console.log(
      "[FOCKIS MESSAGES] Initializing real-time socket hook",
    );

    /* ========================================================================
       MESSAGE NEW
    ======================================================================== */

    const offNew =
      messageSocket.on(
        "message:new",
        ({
          message,
        }) => {
          console.log(
            "[FOCKIS MESSAGES] Incoming message:new",
            message,
          );

          if (!message) {
            console.warn(
              "[FOCKIS MESSAGES] message:new contained no message",
            );

            return;
          }

          receiveMessage(message);
        },
      );

    /* ========================================================================
       MESSAGE DELIVERED
    ======================================================================== */

    const offDelivered =
      messageSocket.on(
        "message:delivered",
        ({
          messageId,
          conversationId,
        }) => {
          console.log(
            "[FOCKIS MESSAGES] message:delivered",
            {
              messageId,
              conversationId,
            },
          );

          useMessagesStore
            .getState()
            .updateMessageStatus(
              String(conversationId),
              String(messageId),
              "delivered",
            );
        },
      );

    /* ========================================================================
       MESSAGE READ
    ======================================================================== */

    const offRead =
      messageSocket.on(
        "message:read",
        ({
          messageId,
          conversationId,
        }) => {
          console.log(
            "[FOCKIS MESSAGES] message:read",
            {
              messageId,
              conversationId,
            },
          );

          useMessagesStore
            .getState()
            .updateMessageStatus(
              String(conversationId),
              String(messageId),
              "read",
            );
        },
      );

    /* ========================================================================
       TYPING START
    ======================================================================== */

    const offTypingStart =
      messageSocket.on(
        "typing:start",
        ({
          conversationId,
          userId,
        }) => {
          setTyping(
            String(conversationId),
            String(userId),
            true,
          );
        },
      );

    /* ========================================================================
       TYPING STOP
    ======================================================================== */

    const offTypingStop =
      messageSocket.on(
        "typing:stop",
        ({
          conversationId,
          userId,
        }) => {
          setTyping(
            String(conversationId),
            String(userId),
            false,
          );
        },
      );

    /* ========================================================================
       PRESENCE
    ======================================================================== */

    const offPresence =
      messageSocket.on(
        "presence:update",
        ({
          userId,
          presence,
          lastSeen,
        }) => {
          updatePresence(
            String(userId),
            presence,
            lastSeen,
          );
        },
      );

    /* ========================================================================
       INCOMING CALL
    ======================================================================== */

    const offIncomingCall =
      messageSocket.onRaw(
        "call:incoming",
        (payload) => {
          console.log(
            "[FOCKIS CALL] Incoming call",
            payload,
          );

          const call =
            buildCall(
              payload,
              "incoming",
            );

          if (!call) {
            return;
          }

          /*
           * Do not overwrite an already active call.
           */
          const current =
            useCallStore.getState();

          if (current.activeCall) {
            console.warn(
              "[FOCKIS CALL] Ignoring incoming call while another call is active",
            );

            return;
          }

          current.setIncomingCall(
            call,
          );
        },
      );

    /* ========================================================================
       CALL ACCEPTED
    ======================================================================== */

    const offCallAccepted =
      messageSocket.onRaw(
        "call:accepted",
        (payload) => {
          console.log(
            "[FOCKIS CALL] Call accepted",
            payload,
          );

          const callId =
            getCallId(payload);

          if (!callId) {
            return;
          }

          const current =
            useCallStore.getState();

          /*
           * Preserve the original outgoing call information when possible.
           *
           * This is important because the original outgoing call may contain
           * participantName and participantAvatar supplied by ChatHeader.
           */
          const outgoing =
            current.outgoingCall;

          const acceptedCall =
            buildCall(
              payload,
              "active",
            );

          if (!acceptedCall) {
            return;
          }

          const mergedCall: Call = {
            ...(outgoing ?? {}),
            ...acceptedCall,

            id: callId,

            type:
              payload?.type ??
              outgoing?.type ??
              acceptedCall.type,

            callerId:
              payload?.callerId ??
              outgoing?.callerId ??
              acceptedCall.callerId,

            receiverId:
              payload?.receiverId ??
              outgoing?.receiverId ??
              acceptedCall.receiverId,

            participantName:
              outgoing?.participantName ??
              acceptedCall.participantName,

            participantAvatar:
              outgoing?.participantAvatar ??
              acceptedCall.participantAvatar,

            createdAt:
              outgoing?.createdAt ??
              acceptedCall.createdAt,

            acceptedAt:
              payload?.acceptedAt ??
              acceptedCall.acceptedAt ??
              new Date().toISOString(),

            status: "active",
          };

          current.acceptCall(
            mergedCall,
          );
        },
      );

    /* ========================================================================
       CALL REJECTED
    ======================================================================== */

    const offCallRejected =
      messageSocket.onRaw(
        "call:rejected",
        (payload) => {
          console.log(
            "[FOCKIS CALL] Call rejected",
            payload,
          );

          const callId =
            getCallId(payload);

          const current =
            useCallStore.getState();

          /*
           * If the server included a callId, only clear that call.
           *
           * If no callId exists, clear the currently displayed call for
           * backwards compatibility.
           */
          if (
            callId &&
            current.outgoingCall &&
            current.outgoingCall.id !== callId &&
            current.incomingCall?.id !== callId
          ) {
            return;
          }

          current.rejectCall();
        },
      );

    /* ========================================================================
       CALL ENDED
    ======================================================================== */

    const offCallEnded =
      messageSocket.onRaw(
        "call:ended",
        (payload) => {
          console.log(
            "[FOCKIS CALL] Call ended",
            payload,
          );

          const callId =
            getCallId(payload);

          const current =
            useCallStore.getState();

          /*
           * Do not let an old/stale call:ended event terminate a newer call.
           */
          if (callId) {
            const activeId =
              current.activeCall?.id;

            const outgoingId =
              current.outgoingCall?.id;

            const incomingId =
              current.incomingCall?.id;

            const matches =
              activeId === callId ||
              outgoingId === callId ||
              incomingId === callId;

            if (!matches) {
              console.warn(
                "[FOCKIS CALL] Ignoring stale call:ended event",
                {
                  callId,
                  activeId,
                  outgoingId,
                  incomingId,
                },
              );

              return;
            }
          }

          current.endCall();
        },
      );

    /* ========================================================================
       WEBRTC OFFER
    ======================================================================== */

    const offWebRTCOffer =
      messageSocket.onRaw(
        "webrtc:offer",
        (payload) => {
          console.log(
            "[FOCKIS WEBRTC] Offer received",
            {
              callId: payload?.callId,
              senderId: payload?.senderId,
            },
          );

          /*
           * The actual peer connection handler subscribes to this same
           * messageSocket raw event.
           *
           * We intentionally do not create RTCPeerConnection here.
           */
        },
      );

    /* ========================================================================
       WEBRTC ANSWER
    ======================================================================== */

    const offWebRTCAnswer =
      messageSocket.onRaw(
        "webrtc:answer",
        (payload) => {
          console.log(
            "[FOCKIS WEBRTC] Answer received",
            {
              callId: payload?.callId,
              senderId: payload?.senderId,
            },
          );
        },
      );

    /* ========================================================================
       WEBRTC ICE CANDIDATE
    ======================================================================== */

    const offWebRTCICE =
      messageSocket.onRaw(
        "webrtc:ice-candidate",
        (payload) => {
          console.log(
            "[FOCKIS WEBRTC] ICE candidate received",
            {
              callId: payload?.callId,
              senderId: payload?.senderId,
            },
          );
        },
      );

    /* ========================================================================
       CONNECT AFTER LISTENERS ARE REGISTERED
    ======================================================================== */

    /*
     * Register all React-level listeners BEFORE connecting.
     *
     * This prevents a very fast socket connection/event from occurring before
     * this hook has attached its handlers.
     */
    messageSocket.connect();

    /* ========================================================================
       CLEANUP
    ======================================================================== */

    return () => {
      console.log(
        "[FOCKIS MESSAGES] Cleaning up real-time socket hook",
      );

      offNew();

      offDelivered();

      offRead();

      offTypingStart();

      offTypingStop();

      offPresence();

      offIncomingCall();

      offCallAccepted();

      offCallRejected();

      offCallEnded();

      offWebRTCOffer();

      offWebRTCAnswer();

      offWebRTCICE();

      messageSocket.disconnect();
    };
  }, [
    setTyping,
    receiveMessage,
    updatePresence,
  ]);
}