import {
  IsIn,
  IsMongoId,
  IsOptional,
  IsString,
} from "class-validator";

/* ============================================================================
   VIDEO AD EVENT DTO

   Events generated by a video advertisement.

   Supported:

     IMPRESSION
     CLICK
     CLOSE
     SKIP

   NOTE:
   The video advertisement returned by MarketingService is backed by a
   Campaign document. Therefore campaignId is the identifier used when
   recording the event.
============================================================================ */

export class VideoAdEventDto {
  /* ==========================================================================
     CAMPAIGN / ADVERTISEMENT ID
  ========================================================================== */

  @IsMongoId()
  campaignId!: string;

  /* ==========================================================================
     VIDEO ID

     Optional because a video advertisement may not have a separate
     video database record.
  ========================================================================== */

  @IsOptional()
  @IsString()
  videoId?: string;

  /* ==========================================================================
     EVENT
  ========================================================================== */

  @IsIn([
    "IMPRESSION",
    "CLICK",
    "CLOSE",
    "SKIP",
  ])
  event!:
    | "IMPRESSION"
    | "CLICK"
    | "CLOSE"
    | "SKIP";
}